// Staking
export const STAKING_CONTRACT_ADDRESS = import.meta.env.VITE_STAKING_CONTRACT_ADDRESS;

// Funding
export const DAO_FUNDING_CONTRACT_ADDRESS = import.meta.env.VITE_DAO_FUNDING_CONTRACT_ADDRESS;
export const DAO_VIEW_CONTRACT_ADDRESS = import.meta.env.VITE_DAO_VIEW_CONTRACT_ADDRESS;

